#!/bin/bash
#/ Usage: bin/strap.sh [--debug]

# see: https://github.com/MikeMcQuaid/strap/blob/master/bin/strap.sh

cd $(dirname $0)/..
ln -sf ~/.dotfiles/Brewfile ~/.Brewfile
brew bundle --global


# iTerm2 Preferences Folder Location
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.dotfiles/iterm2"
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true

# Rectangle Alternate Default Shortcuts and TODO mode
defaults write com.knollsoft.Rectangle alternateDefaultShortcuts -bool true
defaults write com.knollsoft.Rectangle todo -int 1

echo "Done configuring macOS!"
